/**
 * Consent form templates + renderer.
 *
 * This module is shared by the browser (form builder, signing page) and the
 * server (email + frozen document render), so it must stay free of React,
 * DOM and Node-only imports.
 *
 * The three templates mirror the outreach drip segments: real estate,
 * estate planning, and hospital / nursing home.
 */

import type {
  ConsentTemplate,
  ConsentTemplateId,
  ConsentAcknowledgement,
} from '../types/consent';

/** Acknowledgements every template carries — these are what make the signature hold up. */
const BASE_ACKNOWLEDGEMENTS: ConsentAcknowledgement[] = [
  {
    key: 'notAnAttorney',
    label:
      'I understand the notary public is not an attorney and cannot give legal advice, prepare legal documents, or explain the contents or effect of any document.',
    required: true,
  },
  {
    key: 'validId',
    label:
      'I will present valid, unexpired, government-issued photo identification at the appointment, and I understand the notarization cannot proceed without it.',
    required: true,
  },
  {
    key: 'willingAndAware',
    label:
      'I am signing willingly, of my own free will, and I am aware of the nature of the documents being notarized.',
    required: true,
  },
  {
    key: 'journalRecord',
    label:
      'I consent to the notary recording this notarial act in their official journal, including my name, the type of document, the identification presented, and the date and time.',
    required: true,
  },
  {
    key: 'feesUnderstood',
    label:
      'I have reviewed the Cost of Services total above, I agree to that amount, and I understand travel reimbursement is separate from the statutory notarial fee.',
    required: true,
  },
];

const COMMON_FIELDS = [
  { key: 'clientName',       label: 'Client / Signer Name', type: 'text' as const,     required: true,  prefillFrom: 'fullName' as const },
  { key: 'clientEmail',      label: 'Client Email',         type: 'text' as const,     required: true,  prefillFrom: 'email' as const },
  { key: 'clientPhone',      label: 'Client Phone',         type: 'text' as const,     prefillFrom: 'phone' as const },
  { key: 'appointmentDate',  label: 'Appointment Date',     type: 'date' as const,     required: true },
  { key: 'appointmentTime',  label: 'Appointment Time',     type: 'time' as const,     required: true },
  { key: 'appointmentLocation', label: 'Appointment Location', type: 'textarea' as const, required: true, placeholder: 'Street, city, state, ZIP', prefillFrom: 'address' as const },
  { key: 'notarialFee',      label: 'Fee per Notarized Signature', type: 'currency' as const, required: true, help: 'North Carolina caps most acknowledgments at $10.00 per principal signature.' },
  { key: 'actCount',         label: 'Number of Notarized Signatures', type: 'number' as const, required: true, help: 'Fee per signature times this count is shown to the client as a line item.' },
  { key: 'travelFee',        label: 'Travel / Convenience Fee', type: 'currency' as const, help: 'Must be disclosed and agreed to in advance, separately from the notarial fee.' },
];

/** Clauses appended to every template, after the template-specific ones. */
const BASE_CLAUSES = [
  {
    heading: 'Scope of Service',
    body:
      '{{business.name}} is a commissioned notary public providing notarial services only. The notary will verify the identity of each signer, confirm each signer is signing willingly and is aware of the contents of the document, witness the signature, and complete the notarial certificate. The notary does not draft, select, review, correct, or explain documents.',
  },
  {
    heading: 'Not Legal or Financial Advice',
    body:
      'The notary is not an attorney licensed to practice law and may not give legal advice about your documents, accept fees for legal advice, or recommend how you should sign. If you need your documents explained, please consult a licensed attorney before the appointment.',
  },
  {
    heading: 'Fees',
    body:
      'The notarial fee is {{notarialFee}} per notarized signature, with {{actCount}} signature(s) anticipated, plus travel reimbursement of {{travelFee}}. The itemised total shown in the Cost of Services table above is what is due at the time of service. Travel reimbursement is charged for the time and expense of traveling to you and is separate from, and clearly distinguishable from, the statutory notarial fee. If the number of signatures turns out to be different on the day, the notarial fee changes accordingly and is confirmed with you before it is charged.',
  },
  {
    heading: 'Mileage and Travel Reimbursement',
    body:
      'Travel is billed as mileage reimbursement at the IRS business rate of $0.725 per mile, calculated on round-trip distance from our office in Mint Hill, NC. Travel reimbursement is not a notarial fee and is stated separately from it, as required. Any estimate given before the appointment — including one generated by the website quote calculator — is an estimate only; the final figure is the one stated in this form. If the appointment address changes, a second trip is needed, or the route differs materially from the estimate, the travel amount is recalculated and confirmed with you before any additional charge applies.',
  },
  {
    heading: 'Identification Required',
    body:
      'Every signer must present valid, unexpired, government-issued photo identification at the appointment. Acceptable forms include a driver license, state-issued identification card, United States passport, or military identification. Without acceptable identification, the notary is required to refuse the notarization, and the travel fee remains payable.',
  },
  {
    heading: 'Right to Refuse a Notarization',
    body:
      'The notary must refuse to perform a notarial act if the signer cannot be properly identified, appears confused or unaware of the nature of the transaction, appears to be signing under duress or undue influence, or if the document is incomplete or blank. A refusal on these grounds is required by law and is not a reflection on the signer.',
  },
  {
    heading: 'Journal and Recordkeeping',
    body:
      'The notary maintains a journal of notarial acts as required by law. Entries include the date and time of the act, the type of act, the type of document, the name and address of each signer, and the type of identification relied upon. Journal entries are retained for the period required by state law and are released only as the law permits or requires.',
  },
  {
    heading: 'Cancellation and Rescheduling',
    body:
      'Please give as much notice as possible if you need to cancel or reschedule. If the notary travels to the appointment location and the signing cannot be completed — for example, because a signer is unavailable, identification is missing, or documents have not arrived — the agreed travel fee remains payable.',
  },
  {
    heading: 'Privacy of Your Information',
    body:
      'Information collected for this appointment is used to schedule the appointment, complete and record the notarial act, and bill for services. It is not sold. It is disclosed only to complete the transaction you have requested, or where required by law.',
  },
  {
    heading: 'Consent to Do Business Electronically',
    body:
      'By signing electronically below, you agree that your electronic signature is the legal equivalent of your handwritten signature on this consent form, that you intend it to be binding, and that this record may be delivered and retained electronically. You may request a paper copy of this form at no charge, and you may withdraw consent to electronic delivery at any time, by contacting {{business.name}}{{business.emailSuffix}}. Withdrawing consent does not affect the validity of records already signed. To view and retain this record you need a device with an internet connection, a current web browser, and the ability to receive email and open PDF files.',
  },
  {
    heading: 'Scope of This Consent',
    body:
      'This form is a consent and disclosure for notarial services. It is not the document being notarized, and signing it does not notarize anything. It does not create an attorney-client relationship and is not a substitute for legal advice.',
  },
];

export const CONSENT_TEMPLATES: ConsentTemplate[] = [
  {
    id: 'general-notary',
    name: 'General Notary Work',
    description: 'Vehicle titles, powers of attorney, affidavits, bills of sale, and single documents.',
    segment: 'General',
    documentTitle: 'Client Consent & Disclosure — General Notary Services',
    fields: [
      ...COMMON_FIELDS,
      { key: 'documentTypes',   label: 'Documents to Be Notarized', type: 'textarea', required: true, placeholder: 'e.g. NC vehicle title (seller signature), durable power of attorney, affidavit of residency, bill of sale' },
      { key: 'signerNames',     label: 'All Signers',           type: 'textarea', required: true, placeholder: 'Everyone whose signature must be notarized. Each needs their own valid photo ID.', prefillFrom: 'fullName' },
      { key: 'vehicleInfo',     label: 'Vehicle / VIN',         type: 'text', help: 'Title work only. Leave blank otherwise.' },
      { key: 'witnessesNeeded', label: 'Witnesses Required',    type: 'select', options: ['None', 'One (1)', 'Two (2)', 'Unsure — please advise'] },
      { key: 'apostilleNeeded', label: 'Apostille Requested',   type: 'select', options: ['No', 'Yes'], help: 'The notary cannot issue an apostille; it is obtained from the Secretary of State afterward.' },
    ],
    clauses: [
      {
        heading: 'Nature of This Appointment',
        body:
          'This appointment is to notarize the following for {{signerNames}}: {{documentTypes}}. The notary will verify identity, confirm each signer is signing willingly and knowingly, witness the signature, and complete the notarial certificate.',
      },
      {
        heading: 'Documents Must Not Be Signed in Advance',
        body:
          'Do not sign your documents before the appointment. The notary must personally witness each signature that is being notarized. A document already bearing a signature cannot be notarized, and the signer would have to sign a fresh copy. This applies to vehicle titles, which are frequently spoiled this way.',
      },
      {
        heading: 'Vehicle Titles and Transfer Documents',
        body:
          'For title work on {{vehicleInfo}}, please understand what the notary can and cannot do. The notary witnesses the signature only. The notary does not verify who owns the vehicle, does not confirm the odometer reading, does not check for liens, and cannot tell you which boxes to complete, how to state the sale price, or what to write on the odometer or damage disclosure. Those entries are your statements, and questions about them belong with the NCDMV, a license plate agency, or your attorney. Titles with erasures, correction fluid, cross-outs, or the wrong name in a field are commonly rejected by the DMV, and the notary may decline a title that appears altered.',
      },
      {
        heading: 'Every Signer Must Appear in Person',
        body:
          'Each person whose signature is being notarized must be physically present with their own valid, unexpired, government-issued photo identification. One person cannot sign for another without properly executed authority presented at the appointment, and a signer cannot be added by phone or video.',
      },
      {
        heading: 'Complete Documents Only',
        body:
          'The notary cannot notarize a document with blank spaces in the areas being certified, and cannot notarize a photocopy of a signature or a document you have not read. Please bring the complete document, including any pages the notarial certificate refers to.',
      },
      {
        heading: 'Choosing the Notarial Act',
        body:
          'The notary cannot choose the type of notarial act for you. If your document does not state whether it needs an acknowledgment, a jurat, or an oath, you must ask the receiving agency — the DMV, the court, the bank, or the requesting party — before the appointment. Selecting it for you would be the unauthorized practice of law.',
      },
      {
        heading: 'Witnesses',
        body:
          'Witnesses required for this appointment: {{witnessesNeeded}}. If witnesses are needed, please arrange them in advance. Witnesses must be adults with identification, and the notary cannot serve as a witness to a document they are notarizing.',
      },
      {
        heading: 'Apostille and Authentication',
        body:
          'Apostille requested: {{apostilleNeeded}}. An apostille is issued by the Secretary of State, not by the notary. The notary can complete a notarization in the form the Secretary of State requires, but obtaining, paying for, and submitting for the apostille is a separate step handled after this appointment.',
      },
      ...BASE_CLAUSES,
    ],
    acknowledgements: [
      ...BASE_ACKNOWLEDGEMENTS,
      {
        key: 'notPreSigned',
        label:
          'My documents will be unsigned when we meet, and I understand a signature made before the appointment cannot be notarized.',
        required: true,
      },
      {
        key: 'signersPresent',
        label: 'Every person whose signature must be notarized will be present with their own valid photo ID.',
        required: true,
      },
      {
        key: 'actChosen',
        label:
          'I understand the notary cannot decide which notarial act my document needs, or tell me how to fill it out — including on a vehicle title.',
        required: true,
      },
    ],
  },

  {
    id: 'real-estate',
    name: 'Real Estate / Loan Signing',
    description: 'Closings, refinances, HELOCs, and seller packages handled as a signing agent.',
    segment: 'Real Estate',
    documentTitle: 'Client Consent & Disclosure — Real Estate Loan Signing',
    fields: [
      ...COMMON_FIELDS,
      { key: 'propertyAddress', label: 'Property Address',   type: 'textarea', required: true, prefillFrom: 'propertyAddress' },
      { key: 'transactionType', label: 'Transaction Type',   type: 'select', required: true, options: ['Purchase', 'Refinance', 'HELOC', 'Seller Package', 'Reverse Mortgage', 'Loan Modification', 'Other'] },
      { key: 'lenderName',      label: 'Lender',             type: 'text' },
      { key: 'titleCompany',    label: 'Title / Escrow Company', type: 'text' },
      { key: 'escrowNumber',    label: 'Loan / Escrow Number', type: 'text' },
      { key: 'coSignerName',    label: 'Co-Signer Name',     type: 'text', prefillFrom: 'spouseName', help: 'Every signer must be present with their own valid ID.' },
      { key: 'docReturnMethod', label: 'Document Return Method', type: 'select', options: ['Prepaid overnight label', 'Drop at shipping location', 'Scan-back then ship', 'Hand delivery', 'Other'] },
    ],
    clauses: [
      {
        heading: 'Nature of This Appointment',
        body:
          'This appointment is a {{transactionType}} signing for the property at {{propertyAddress}}, arranged through {{titleCompany}} for {{lenderName}} under loan/escrow number {{escrowNumber}}. The notary acts as a signing agent: presenting your closing package, directing you to each signature, date, and initial line, notarizing the documents that require it, and returning the executed package.',
      },
      {
        heading: 'The Notary Cannot Explain Your Loan',
        body:
          'The notary cannot advise you on your interest rate, payment amount, closing costs, prepayment penalties, escrow amounts, or any other term of your loan, and cannot tell you whether you should sign. Questions about loan terms must be directed to your lender, loan officer, escrow officer, or attorney. If a term does not look correct to you, stop and call them before signing — do not rely on the notary.',
      },
      {
        heading: 'All Signers Must Be Present',
        body:
          'Every person signing the package — including {{coSignerName}} where listed — must be physically present at the appointment with their own valid, unexpired, government-issued photo identification. The notary cannot notarize for an absent signer, cannot accept a signature made in advance, and cannot allow one signer to sign on behalf of another without properly executed and presented authority.',
      },
      {
        heading: 'Document Handling and Return',
        body:
          'Your executed package will be returned by: {{docReturnMethod}}. The notary handles your package as confidential, keeps it secure from the time it is printed to the time it is returned, and does not retain copies of your loan documents beyond what is required for the journal entry.',
      },
      {
        heading: 'Incomplete or Late Packages',
        body:
          'If the signing cannot be completed because documents have not arrived, arrive incomplete, contain errors requiring lender correction, or a signer is unavailable or unidentifiable, the appointment will be rescheduled and the agreed travel fee remains payable for the trip made.',
      },
      ...BASE_CLAUSES,
    ],
    acknowledgements: [
      ...BASE_ACKNOWLEDGEMENTS,
      {
        key: 'lenderQuestions',
        label:
          'I understand that all questions about my loan terms, closing costs, and figures must go to my lender, escrow officer, or attorney — not the notary.',
        required: true,
      },
      {
        key: 'allSignersPresent',
        label: 'All signers listed on the documents will be present at the appointment with their own valid photo ID.',
        required: true,
      },
    ],
  },

  {
    id: 'estate-planning',
    name: 'Estate Planning Documents',
    description: 'Wills, trusts, powers of attorney, healthcare directives, and deeds.',
    segment: 'Estate Planning',
    documentTitle: 'Client Consent & Disclosure — Estate Planning Document Signing',
    fields: [
      ...COMMON_FIELDS,
      { key: 'documentTypes',    label: 'Documents to Be Notarized', type: 'textarea', required: true, placeholder: 'e.g. Revocable living trust, pour-over will, durable power of attorney, healthcare power of attorney, living will' },
      { key: 'attorneyName',     label: 'Drafting Attorney / Firm',  type: 'text', help: 'Leave blank if the client prepared the documents without counsel.' },
      { key: 'witnessesNeeded',  label: 'Witnesses Required',        type: 'select', required: true, options: ['None', 'One (1)', 'Two (2)'] },
      { key: 'witnessesProvidedBy', label: 'Witnesses Provided By',  type: 'select', options: ['Client', 'Notary (arranged in advance)', 'Attorney office', 'Not applicable'] },
      { key: 'principalName',    label: 'Principal / Grantor Name',  type: 'text', prefillFrom: 'fullName' },
    ],
    clauses: [
      {
        heading: 'Nature of This Appointment',
        body:
          'This appointment is to notarize estate planning documents for {{principalName}}, specifically: {{documentTypes}}. Where a drafting attorney is involved ({{attorneyName}}), the notary works only within the signing instructions that attorney provides.',
      },
      {
        heading: 'The Notary Did Not Prepare These Documents',
        body:
          'The notary did not draft, select, or review your estate planning documents and cannot tell you whether they accomplish what you intend, whether a will or a trust is right for you, how your property will pass, or what tax consequences may follow. Those are legal questions for a licensed attorney. If your documents were prepared without an attorney, please understand that the notary is not able to check them for you.',
      },
      {
        heading: 'Witnesses',
        body:
          'This signing requires: {{witnessesNeeded}} witness(es), to be provided by {{witnessesProvidedBy}}. Witnesses must be adults, must be present for the entire signing, and generally should be disinterested — that is, not named as a beneficiary, fiduciary, or heir, and not a spouse of one. The notary cannot serve as a witness to a document they are also notarizing.',
      },
      {
        heading: 'Capacity and Free Will',
        body:
          'The notary must be satisfied that the principal appears aware of what they are signing and is acting of their own free will, without duress or undue influence. If the principal appears confused, cannot communicate their intent, or appears to be directed by another person present, the notary is required to decline the notarization. Determining legal capacity is a matter for a physician and an attorney, not the notary, and the notary makes no determination of legal capacity.',
      },
      {
        heading: 'Third Parties Present',
        body:
          'Family members and caregivers may be present for comfort, but the principal must answer for themselves and sign for themselves. The notary may ask others to step back or step out of the room briefly to confirm the principal is signing freely.',
      },
      {
        heading: 'Original Documents',
        body:
          'Estate planning documents are usually valid only as executed originals. The notary does not retain your originals and does not keep copies of the documents beyond the journal entry. Store your originals safely and tell your executor, trustee, or agent where to find them.',
      },
      ...BASE_CLAUSES,
    ],
    acknowledgements: [
      ...BASE_ACKNOWLEDGEMENTS,
      {
        key: 'attorneyQuestions',
        label:
          'I understand the notary did not prepare these documents and cannot advise me on whether they accomplish my wishes; those questions go to a licensed attorney.',
        required: true,
      },
      {
        key: 'witnessesArranged',
        label: 'I understand the witness requirement stated above and who is responsible for providing witnesses.',
        required: true,
      },
      {
        key: 'noUndueInfluence',
        label:
          'I am signing free of pressure from any family member, caregiver, or other person, and the decisions in these documents are my own.',
        required: true,
      },
    ],
  },

  {
    id: 'hospital-facility',
    name: 'Hospital / Nursing Home Signing',
    description: 'Bedside signings at hospitals, rehabilitation centers, hospice, and care facilities.',
    segment: 'Hospital & Nursing Home',
    documentTitle: 'Client Consent & Disclosure — Hospital / Care Facility Signing',
    fields: [
      ...COMMON_FIELDS,
      { key: 'facilityName',      label: 'Facility Name',          type: 'text', required: true },
      { key: 'facilityAddress',   label: 'Facility Address',       type: 'textarea', required: true },
      { key: 'roomNumber',        label: 'Room / Unit Number',     type: 'text' },
      { key: 'signerName',        label: 'Patient / Signer Name',  type: 'text', required: true },
      { key: 'requestedBy',       label: 'Appointment Requested By', type: 'text', required: true, prefillFrom: 'fullName', help: 'Person arranging the appointment, if not the patient.' },
      { key: 'requestorRelationship', label: 'Relationship to Signer', type: 'text', placeholder: 'e.g. daughter, attorney, case manager' },
      { key: 'documentTypes',     label: 'Documents to Be Notarized', type: 'textarea', required: true },
      { key: 'witnessesNeeded',   label: 'Witnesses Required',     type: 'select', required: true, options: ['None', 'One (1)', 'Two (2)'] },
      { key: 'witnessSource',     label: 'Witnesses Provided By',  type: 'select', options: ['Family', 'Facility staff', 'Notary (arranged in advance)', 'Not applicable'] },
    ],
    clauses: [
      {
        heading: 'Nature of This Appointment',
        body:
          'This is a bedside notarization for {{signerName}} at {{facilityName}}, {{facilityAddress}}, room {{roomNumber}}. The appointment was requested by {{requestedBy}} ({{requestorRelationship}}). The documents to be notarized are: {{documentTypes}}.',
      },
      {
        heading: 'The Signer Must Be Awake, Aware, and Able to Communicate',
        body:
          'The notary must speak directly with the signer. The signer must be awake and responsive, must be able to communicate that they understand they are signing a document and what kind of document it is, and must be able to indicate their intent without being coached. Sedation, pain medication, confusion, or fatigue may make notarization impossible at that moment. If so, the notary will suggest returning at a better time of day.',
      },
      {
        heading: 'No Determination of Medical or Legal Capacity',
        body:
          'The notary is not a physician and is not an attorney. The notary makes no determination of the signer\'s medical or legal capacity. The notary only observes whether the signer appears aware of the nature of the act and is acting willingly at that moment. If the signer\'s capacity is in question, obtain a physician\'s assessment and consult an attorney before scheduling.',
      },
      {
        heading: 'Signing Free of Influence',
        body:
          'The signer must sign of their own free will. The notary may ask family members, caregivers, or facility staff to step away from the bedside so the notary can speak with the signer privately. If it appears the signer is being pressured or directed, or that someone else is answering for them, the notary is required to decline. This protection exists for the signer\'s benefit.',
      },
      {
        heading: 'If the Signer Cannot Sign by Hand',
        body:
          'A signer physically unable to sign may be able to make a mark, or to direct another person to sign their name in their presence and at their direction, with witnesses. This depends on the document and state law, and the requirements must be confirmed before the appointment. Please raise this in advance so it does not delay the signing.',
      },
      {
        heading: 'Witnesses',
        body:
          'This signing requires {{witnessesNeeded}} witness(es), provided by {{witnessSource}}. Please note that many facilities restrict their staff from acting as witnesses, and staff are typically unavailable on short notice. Confirm witnesses in advance. Witnesses should be disinterested — not a beneficiary, agent, or heir under the document.',
      },
      {
        heading: 'Facility Access and Timing',
        body:
          'Access depends entirely on the facility. Visiting hours, infection-control precautions, isolation status, staff availability, and the signer\'s treatment schedule can all delay or prevent the appointment. Please clear the visit with the facility and the care team in advance. If the notary arrives and cannot gain access or the signer is not available, the travel fee remains payable.',
      },
      {
        heading: 'Health Information',
        body:
          'The notary does not request or record medical information and will not document a diagnosis or treatment in the journal. The journal records only what the law requires: the act performed, the document type, the signer\'s name and address, the identification relied upon, and the date, time, and location.',
      },
      ...BASE_CLAUSES,
    ],
    acknowledgements: [
      ...BASE_ACKNOWLEDGEMENTS,
      {
        key: 'signerAware',
        label:
          'The signer is expected to be awake, responsive, and able to communicate at the scheduled time, and I understand the notary must decline if they are not.',
        required: true,
      },
      {
        key: 'noCapacityJudgment',
        label:
          'I understand the notary makes no determination of medical or legal capacity and that a physician or attorney should be consulted if capacity is in question.',
        required: true,
      },
      {
        key: 'facilityAccess',
        label:
          'I have confirmed, or will confirm, that the facility permits this visit at the scheduled time, and I understand the travel fee applies if access is denied.',
        required: true,
      },
      {
        key: 'witnessesConfirmed',
        label: 'I understand the witness requirement above and that facility staff often cannot serve as witnesses.',
        required: true,
      },
    ],
  },
];

export function getConsentTemplate(id: ConsentTemplateId | string): ConsentTemplate | undefined {
  return CONSENT_TEMPLATES.find(t => t.id === id);
}

export interface RenderBusiness {
  name: string;
  email?: string;
  phone?: string;
  location?: string;
  website?: string;
  commissionNumber?: string;
  commissionExpiration?: string;
}

export function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const CURRENCY_FIELDS = new Set(['notarialFee', 'travelFee']);

function toNumber(raw: string | undefined): number {
  const n = Number(String(raw ?? '').replace(/[^0-9.\-]/g, ''));
  return Number.isFinite(n) && n >= 0 ? n : 0;
}

function money(n: number): string {
  return `$${n.toFixed(2)}`;
}

export interface ConsentCostBreakdown {
  feePerSignature: number;
  signatureCount: number;
  notarialSubtotal: number;
  travelFee: number;
  total: number;
}

/**
 * Itemised cost the client sees before signing.
 *
 * The per-signature fee is multiplied out rather than left for the client to
 * work out, so the number they agree to is the number they will be charged.
 */
export function computeConsentCost(fields: Record<string, string>): ConsentCostBreakdown {
  const feePerSignature = toNumber(fields.notarialFee);
  const signatureCount = Math.max(0, Math.floor(toNumber(fields.actCount)));
  const travelFee = toNumber(fields.travelFee);
  const notarialSubtotal = Math.round(feePerSignature * signatureCount * 100) / 100;
  return {
    feePerSignature,
    signatureCount,
    notarialSubtotal,
    travelFee,
    total: Math.round((notarialSubtotal + travelFee) * 100) / 100,
  };
}

/** Formats a stored field value for display; empty values become a neutral placeholder. */
export function formatFieldValue(key: string, raw: string | undefined): string {
  const value = (raw ?? '').trim();
  if (!value) return CURRENCY_FIELDS.has(key) ? '$0.00' : 'not specified';
  if (CURRENCY_FIELDS.has(key)) {
    const num = Number(value.replace(/[^0-9.\-]/g, ''));
    return Number.isFinite(num) ? `$${num.toFixed(2)}` : value;
  }
  if (key === 'appointmentDate') {
    // Render as a plain, unambiguous date without pulling in a date library.
    const m = value.match(/^(\d{4})-(\d{2})-(\d{2})$/);
    if (m) {
      const months = ['January','February','March','April','May','June','July','August','September','October','November','December'];
      return `${months[Number(m[2]) - 1]} ${Number(m[3])}, ${m[1]}`;
    }
  }
  return value;
}

/** Replaces {{fieldKey}} and {{business.x}} tokens in clause text. */
export function interpolate(
  text: string,
  fields: Record<string, string>,
  business: RenderBusiness,
): string {
  return text.replace(/\{\{\s*([\w.]+)\s*\}\}/g, (_match, token: string) => {
    if (token.startsWith('business.')) {
      const prop = token.slice('business.'.length);
      if (prop === 'emailSuffix') return business.email ? ` at ${business.email}` : '';
      const val = (business as any)[prop];
      return String(val ?? '');
    }
    return formatFieldValue(token, fields[token]);
  });
}

/**
 * Renders the consent document body as standalone HTML.
 *
 * The output is frozen onto the form when it is sent, so the signer's
 * signature is tied to the exact words they saw — editing the template later
 * cannot retroactively change a signed record.
 */
export function renderConsentDocument(opts: {
  template: ConsentTemplate;
  fields: Record<string, string>;
  business: RenderBusiness;
}): string {
  const { template, fields, business } = opts;

  const cost = computeConsentCost(fields);

  const summaryRows: Array<[string, string]> = [
    ['Client / Signer', formatFieldValue('clientName', fields.clientName)],
    ['Appointment', `${formatFieldValue('appointmentDate', fields.appointmentDate)} at ${formatFieldValue('appointmentTime', fields.appointmentTime)}`],
    ['Location', formatFieldValue('appointmentLocation', fields.appointmentLocation)],
    ['Notary', business.name],
  ];
  if (business.commissionNumber) {
    summaryRows.push(['Commission Number', business.commissionNumber]);
  }
  if (business.commissionExpiration) {
    summaryRows.push(['Commission Expires', business.commissionExpiration]);
  }

  const summary = summaryRows
    .map(
      ([label, value]) => `
      <tr>
        <th style="text-align:left;padding:8px 16px 8px 0;color:#64748b;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:0.04em;vertical-align:top;white-space:nowrap;">${escapeHtml(label)}</th>
        <td style="padding:8px 0;color:#0f172a;font-size:14px;vertical-align:top;">${escapeHtml(value)}</td>
      </tr>`,
    )
    .join('');

  const clauses = template.clauses
    .map(
      (c, i) => `
    <section style="margin:0 0 22px;">
      <h3 style="margin:0 0 6px;font-size:14px;font-weight:700;color:#1e3a5f;">${i + 1}. ${escapeHtml(c.heading)}</h3>
      <p style="margin:0;font-size:14px;line-height:1.75;color:#334155;">${escapeHtml(interpolate(c.body, fields, business))}</p>
    </section>`,
    )
    .join('');

  const costRow = (label: string, detail: string, amount: string, bold = false) => `
      <tr>
        <td style="padding:10px 16px 10px 0;vertical-align:top;">
          <div style="font-size:${bold ? '15' : '14'}px;font-weight:${bold ? '700' : '600'};color:#0f172a;">${escapeHtml(label)}</div>
          ${detail ? `<div style="font-size:12px;color:#64748b;margin-top:2px;">${escapeHtml(detail)}</div>` : ''}
        </td>
        <td style="padding:10px 0;text-align:right;vertical-align:top;white-space:nowrap;font-size:${bold ? '18' : '14'}px;font-weight:${bold ? '800' : '600'};color:${bold ? '#1e3a5f' : '#0f172a'};">${escapeHtml(amount)}</td>
      </tr>`;

  const costTable = `
  <section style="margin:0 0 24px;border:1px solid #e2e8f0;border-radius:10px;overflow:hidden;">
    <div style="background:#1e3a5f;padding:10px 16px;">
      <h2 style="margin:0;font-size:13px;font-weight:700;color:#ffffff;letter-spacing:0.04em;text-transform:uppercase;">Cost of Services</h2>
    </div>
    <table style="border-collapse:collapse;width:100%;padding:0 16px;">
      ${costRow(
        'Notarial fee',
        `${cost.signatureCount} notarized signature${cost.signatureCount === 1 ? '' : 's'} × ${money(cost.feePerSignature)} each`,
        money(cost.notarialSubtotal),
      )}
      ${costRow('Travel reimbursement', 'Round-trip mileage, agreed in advance', money(cost.travelFee))}
      <tr><td colspan="2" style="border-top:1px solid #e2e8f0;padding:0;"></td></tr>
      ${costRow('Total due at appointment', '', money(cost.total), true)}
    </table>
    <p style="margin:0;padding:0 16px 14px;font-size:11px;line-height:1.6;color:#64748b;">
      Payable at the time of service. If the number of signatures changes on the day, the notarial fee changes with it at ${money(cost.feePerSignature)} per signature, and any change is confirmed with you before it is charged.
    </p>
  </section>`;

  return `
<article style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#0f172a;">
  <header style="border-bottom:2px solid #1e3a5f;padding-bottom:16px;margin-bottom:20px;">
    <h1 style="margin:0 0 4px;font-size:20px;font-weight:800;color:#1e3a5f;">${escapeHtml(template.documentTitle)}</h1>
    <p style="margin:0;font-size:13px;color:#64748b;">${escapeHtml(business.name)}${business.location ? ' &bull; ' + escapeHtml(business.location) : ''}${business.phone ? ' &bull; ' + escapeHtml(business.phone) : ''}</p>
  </header>

  <table style="border-collapse:collapse;width:100%;margin:0 0 20px;background:#f8fafc;border-radius:10px;padding:8px;">
    ${summary}
  </table>

  ${costTable}

  ${clauses}
</article>`.trim();
}
