/**
 * Shared attorney lead list — single source of truth.
 * Imported by import-leads.mjs (Firestore import) and
 * personalize-outreach.mjs (AI-personalized outreach).
 *
 * Each lead: { fullName, email, phone, company, title }
 */

export const leads = [
  { fullName: "Michael Phillips", email: "michael@phillipsmccrea.com", phone: "", company: "Phillips and McCrea, PLLC Attorneys at Law", title: "Partner" },
  { fullName: "Dave Levy", email: "dlevy@hedrickgardner.com", phone: "", company: "Gardner Skelton PLLC", title: "Partner" },
  { fullName: "Mark S. Pincus", email: "mark@gardnerskelton.com", phone: "", company: "Gardner Skelton PLLC", title: "Partner" },
  { fullName: "James M (Jim) Anderson", email: "janderson@cattielaw.com", phone: "", company: "Cattie & Gonzalez, PLLC", title: "Partner" },
  { fullName: "Heather Skelton", email: "heather@gardnerskelton.com", phone: "", company: "Gardner Skelton PLLC", title: "Partner" },
  { fullName: "Theresa E. Viera", email: "theresa@modernlegalnc.com", phone: "", company: "Modern Legal", title: "Attorney and Founder" },
  { fullName: "Matthew Marcellino", email: "matt@yourncattorney.com", phone: "", company: "Marcellino & Tyson, PLLC", title: "Partner" },
  { fullName: "Jennifer Moore", email: "jennifer@yourncattorney.com", phone: "", company: "Marcellino & Tyson, PLLC", title: "Partner" },
  { fullName: "Tara Austin Harrawood", email: "tara@yourncattorney.com", phone: "", company: "Marcellino & Tyson, PLLC", title: "Partner" },
  { fullName: "James Davis", email: "james@davislawfirmnc.com", phone: "", company: "Davis & Davis, Attorneys at Law, P.C.", title: "Partner" },
  { fullName: "Henry Pharr III", email: "hpharr@kptlaw.com", phone: "", company: "Kirk Palmer & Thigpen", title: "Partner" },
  { fullName: "Todd Owens", email: "towens@doziermillerlaw.com", phone: "", company: "Dozier Miller Law Group", title: "Mediator, Arbitrator, Attorney, Partner" },
  { fullName: "Austin Baker", email: "austin@mcmillanpllc.com", phone: "", company: "McMillan PLLC", title: "Managing Partner" },
  { fullName: "Gagan Gupta", email: "ggupta@tinfulton.com", phone: "", company: "Tin Fulton Walker & Owen", title: "Partner" },
  { fullName: "Andria Marquez", email: "andria@yourncattorney.com", phone: "", company: "Marcellino & Tyson, PLLC", title: "Partner" },
  { fullName: "Stephanie Ross", email: "sross@doziermillerlaw.com", phone: "", company: "Dozier Miller Law Group", title: "Partner" },
  { fullName: "Clay Campbell", email: "clay@yourncattorney.com", phone: "", company: "Marcellino & Tyson, PLLC", title: "Partner" },
  { fullName: "Jon Carroll", email: "jcarroll@gardnerskelton.com", phone: "", company: "Gardner Skelton PLLC", title: "Partner" },
  { fullName: "William B. Hamel", email: "bhamel@kptlaw.com", phone: "", company: "Kirk Palmer & Thigpen", title: "Partner" },
  { fullName: "Michael Chandler", email: "michael@cvinjurylaw.com", phone: "", company: "Hull & Chandler, P.A.", title: "Personal Injury Attorney / Partner" },
  { fullName: "Beau Wilder", email: "beau@wilderlawgroup.com", phone: "", company: "Wilder Pantazis Law Group", title: "Partner" },
  { fullName: "Kelly Dempsey", email: "kelly@fosterbloomlaw.com", phone: "", company: "Foster + Bloom Family Formation Law Group", title: "Founder / Managing Member" },
  { fullName: "Joshua Mertzlufft", email: "joshua@stake.law", phone: "", company: "Stake", title: "Founder & Patent Attorney" },
  { fullName: "Lauren Lewis", email: "llewis@essexrichards.com", phone: "", company: "Essex Richards", title: "Partner, Attorney at Law" },
  { fullName: "David Murray", email: "david@murraylawfirm.com", phone: "", company: "Murray Law Firm, PLLC", title: "Managing Partner" },
  { fullName: "Jade Cobb Murray", email: "jade@murraylawfirm.com", phone: "", company: "Murray Law Firm, PLLC", title: "Partner" },
  { fullName: "Norris Adams", email: "norris@essexrichards.com", phone: "", company: "Essex Richards", title: "Partner" },
  { fullName: "Sara Lincoln", email: "sara.lincoln@lincolnderr.com", phone: "", company: "Lincoln Derr PLLC", title: "Co-Owner" },
  { fullName: "Ticora Davis", email: "ticora@creatorslawfirm.com", phone: "", company: "The Creator's Law Firm", title: "Founder & Managing Attorney" },
  { fullName: "Harrison Lord", email: "hlord@lordlindley.com", phone: "", company: "Lord & Lindley", title: "Managing Member" },
  { fullName: "Tonya Graser Smith", email: "tonya@grasersmith.com", phone: "", company: "GraserSmith, PLLC", title: "Family Law Attorney and Founder" },
  { fullName: "Rick Mcdermott", email: "rick@mcdermottiplaw.com", phone: "", company: "McDermott IP Law", title: "Founder and Principal" },
  { fullName: "Jason Power", email: "jason@franchise.law", phone: "", company: "Franchise.Law", title: "Owner / Franchise Attorney" },
  { fullName: "Melinda Taylor", email: "melinda@collinsfamilylaw.com", phone: "", company: "Collins Family & Elder Law Group", title: "Partner" },
  { fullName: "Margaret Teich", email: "mteich@tinfulton.com", phone: "", company: "Tin Fulton Walker & Owen", title: "Partner" },
  { fullName: "John T. Daniel", email: "jdaniel@essexrichards.com", phone: "", company: "Essex Richards", title: "Partner" },
  { fullName: "Leigh Anne Williams", email: "leighanne@meridianlawoffice.com", phone: "", company: "Meridian Law Office", title: "Founder & Operating Attorney" },
  { fullName: "Jack Capitano", email: "jcapitano@kptlaw.com", phone: "", company: "Kirk Palmer & Thigpen", title: "Partner" },
  { fullName: "Gregory Hunt", email: "ghunt@ghuntlaw.com", phone: "", company: "Hunt Law, PLLC", title: "Managing Partner" },
  { fullName: "Daniel A Lewis", email: "dlewis@tinfulton.com", phone: "", company: "Tin Fulton Walker & Owen", title: "Partner" },
  { fullName: "Timothy Graham", email: "tgraham@doziermillerlaw.com", phone: "", company: "Dozier Miller Law Group", title: "Partner" },
  { fullName: "Will Terpening", email: "terpening@terpeninglaw.com", phone: "", company: "Terpening Law", title: "Managing Law Partner" },
  { fullName: "Diane Price", email: "diane@jcolaw.com", phone: "", company: "The Olsinski Law Firm, PLLC", title: "Partner" },
  { fullName: "Erika Angles", email: "eangles@jettonmeredithlaw.com", phone: "", company: "Jetton & Meredith, PLLC", title: "Partner" },
  { fullName: "Mark Jetton", email: "markjetton@jettonmeredithlaw.com", phone: "", company: "Jetton & Meredith, PLLC", title: "Owner" },
  { fullName: "Trey Lindley", email: "tlindley@lordlindley.com", phone: "", company: "Lord & Lindley", title: "Managing Member" },
  { fullName: "Claudia L. Soto", email: "claudia@sotolawnc.com", phone: "", company: "Soto Law", title: "Owner & NC Attorney" },
  { fullName: "Keith Nichols", email: "knichols@kptlaw.com", phone: "", company: "Kirk Palmer & Thigpen", title: "Partner" },
  { fullName: "Joe Dye Culik", email: "jdc@dyeculik.com", phone: "", company: "DYE CULIK PC", title: "Principal Attorney + Partner" },
  { fullName: "Zachary Ezor", email: "zezor@tinfulton.com", phone: "", company: "Tin Fulton Walker & Owen", title: "Partner" },
  { fullName: "Grady Ingle", email: "gingle@theinglefirm.com", phone: "", company: "Ingle Law Firm, PA", title: "Founder" },
  { fullName: "Bobby Hinson", email: "bhinson@kptlaw.com", phone: "", company: "Kirk Palmer & Thigpen", title: "Partner" },
  { fullName: "Frances Knox", email: "fknox@knoxlawcenter.com", phone: "", company: "Knox, Brotherton, Knox & Godfrey", title: "Partner" },
  { fullName: "Jason Mcgrath", email: "info@mcgrathspielberger.com", phone: "", company: "McGrath and Spielberger, PLLC", title: "Owner / Partner" },
  { fullName: "Randall Faircloth", email: "randall@regentlawnc.com", phone: "", company: "Regent Law", title: "Managing Partner" },
  { fullName: "Maria Ximena Sussman", email: "maria@sussmanlawfirmpllc.com", phone: "", company: "Sussman Law Firm, PLLC", title: "Managing Attorney and Owner" },
  { fullName: "Allison Holstein", email: "aholstein@doziermillerlaw.com", phone: "", company: "Dozier Miller Law Group", title: "Partner" },
  { fullName: "Karen Schuller Boardman", email: "karen@alignmentlegal.com", phone: "", company: "Alignment Legal", title: "Partner and Co-Founder" },
  { fullName: "Tamara Cornish", email: "tamara.cornish@knipplaw.com", phone: "", company: "Knipp Law Office, PLLC", title: "Partner" },
  { fullName: "Toni Primiano", email: "toni@prjclaw.com", phone: "", company: "Plumides, Romano & Johnson, PC", title: "Partner" },
  { fullName: "Nick Lovelace", email: "nick.lovelace@knipplaw.com", phone: "", company: "Knipp Law Office, PLLC", title: "Attorney / Partner" },
  { fullName: "John Woodman", email: "jwoodman@essexrichards.com", phone: "", company: "Essex Richards", title: "Partner" },
  { fullName: "Allison Vaughn", email: "allison@wilderlawgroup.com", phone: "", company: "Wilder Pantazis Law Group", title: "Partner" },
  { fullName: "Fred Devore", email: "fred@devact.com", phone: "", company: "DeVore, Acton & Stafford, PA", title: "Partner" },
  { fullName: "Eric Spengler", email: "eric@sab.law", phone: "", company: "Spengler & Agans, PLLC", title: "Partner" },
  { fullName: "Tricia Derr", email: "tricia.derr@lincolnderr.com", phone: "", company: "Lincoln Derr PLLC", title: "Co-Owner, Attorney" },
  { fullName: "Crosby Livingston III", email: "crosby@knipplaw.com", phone: "", company: "Knipp Law Office, PLLC", title: "Partner / Attorney" },
  { fullName: "Nicole Gardner", email: "nicole@gardnerskelton.com", phone: "", company: "Gardner Skelton PLLC", title: "Founder & Member" },
  { fullName: "Alexander French", email: "afrench@mcilveenfamilylaw.com", phone: "", company: "McIlveen Family Law", title: "Partner Attorney" },
  { fullName: "Josh Knipp", email: "josh.knipp@knipplaw.com", phone: "", company: "Knipp Law Office, PLLC", title: "Owner / Attorney" },
  { fullName: "Sean P. Smith", email: "sean@grasersmith.com", phone: "", company: "GraserSmith, PLLC", title: "Partner" },
  { fullName: "Ben Thomas", email: "ben@thomasandwebber.com", phone: "", company: "Thomas & Webber - Law At The Lake", title: "Owner" },
  { fullName: "Bill Trosch", email: "troschbill@ctklawyers.com", phone: "", company: "Conrad Trosch & Kemmy, P.A.", title: "Owner" },
  { fullName: "F. William Devore IV", email: "wdevore@devact.com", phone: "", company: "DeVore, Acton & Stafford, PA", title: "Partner" },
  { fullName: "Laura Budd", email: "lbudd@baucomclaytor.com", phone: "", company: "Baucom Claytor", title: "Partner" },
  { fullName: "Jason James", email: "jason@jdlawcarolinas.com", phone: "", company: "James deNobriga Long", title: "Founding Partner" },
  { fullName: "Jake Pickett", email: "jpickett@ltpolaw.com", phone: "", company: "Lancaster, Trotter, Pickett & Owens PLLC", title: "Partner" },
  { fullName: "Kevin Murphy", email: "kevin@herrmannmurphy.com", phone: "", company: "Herrmann & Murphy, PLLC", title: "Partner" },
  { fullName: "J. Gregory Hatcher", email: "ghatcher@hatcherlawgroup.com", phone: "", company: "Hatcher Law Group", title: "Owner & Partner" },
  { fullName: "Alan Guffy", email: "alanguffy@jcdwlaw.com", phone: "", company: "Jones, Childers, Donaldson & Webb, PLLC", title: "Partner" },
  { fullName: "Gary Smith", email: "gary.smith@vennlawgroup.com", phone: "", company: "Venn Law Group", title: "Attorney and Founder" },
  { fullName: "Allen Brotherton", email: "abrotherton@knoxlawcenter.com", phone: "", company: "Knox, Brotherton, Knox & Godfrey", title: "Partner" },
  { fullName: "Chad Buckingham", email: "chad@regentlawnc.com", phone: "", company: "Regent Law", title: "Co-Founder and Partner" },
  { fullName: "Leigh Sellers", email: "leigh.sellers@kruschlaw.com", phone: "", company: "Touchstone Family Law", title: "Founder" },
  { fullName: "Kevin Edwards II", email: "kevin@edwardsinjury.com", phone: "", company: "Edwards Injury Law", title: "Founder" },
  { fullName: "Bryan King", email: "b@bdjalaw.com", phone: "", company: "Bishop, Dulaney, Joyner & Abner, P.A.", title: "Partner" },
  { fullName: "Liscah Isaboke", email: "liscah@isabokelaw.com", phone: "", company: "Isaboke Law Firm", title: "Managing Partner" },
  { fullName: "Jonathon D. Townsend", email: "jonathon.townsend@wagnerhicks.law", phone: "", company: "Wagner Hicks PLLC", title: "Partner" },
  { fullName: "Angela Berland", email: "angela.berland@hankinpacklaw.com", phone: "", company: "Paladin Law", title: "Attorney / Partner" },
  { fullName: "Kevin Donaldson", email: "kevindonaldson@jcdwlaw.com", phone: "", company: "Jones, Childers, Donaldson & Webb, PLLC", title: "Managing Member" },
  { fullName: "Nathan Wenk", email: "nathan@sab.law", phone: "", company: "Spengler & Agans, PLLC", title: "Partner" },
  { fullName: "Sean Herrmann", email: "sean@herrmannmurphy.com", phone: "", company: "Herrmann & Murphy, PLLC", title: "Partner" },
  { fullName: "David Mccleary", email: "dmccleary@doziermillerlaw.com", phone: "", company: "Dozier Miller Law Group", title: "Partner" },
  { fullName: "Woody Connette", email: "wconnette@essexrichards.com", phone: "", company: "Essex Richards", title: "Partner" },
  { fullName: "Eric Meredith", email: "ericmeredith@jettonmeredithlaw.com", phone: "", company: "Jetton & Meredith, PLLC", title: "Attorney / Managing Partner" },
  { fullName: "Brien Bowlin", email: "brien@paladinlawnc.com", phone: "", company: "Paladin Law", title: "Owner / Attorney" },
  { fullName: "Joanna Beck Wilkinson", email: "joanna@fosterbloomlaw.com", phone: "", company: "Foster + Bloom Family Formation Law Group", title: "Attorney, Founding Partner" },
  { fullName: "Adam Denobriga", email: "adam@jdlawcarolinas.com", phone: "", company: "James deNobriga Long", title: "Partner" },
  { fullName: "Todd Capitano", email: "tcapitano@bdjalaw.com", phone: "", company: "Bishop, Dulaney, Joyner & Abner, P.A.", title: "Partner" },
  { fullName: "Dain Dulaney", email: "ddulaney@bdjalaw.com", phone: "", company: "Bishop, Dulaney, Joyner & Abner, P.A.", title: "Shareholder" },
];

export default leads;
